package com.best.pojo;

import java.util.Date;

public class ProductType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_picture_url
     *
     * @mbg.generated
     */
    private String productPictureUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_introduce
     *
     * @mbg.generated
     */
    private String productIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.product_character
     *
     * @mbg.generated
     */
    private String productCharacter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_type.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.t_id
     *
     * @return the value of product_type.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.t_id
     *
     * @param tId the value for product_type.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_name
     *
     * @return the value of product_type.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_name
     *
     * @param productName the value for product_type.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_picture_url
     *
     * @return the value of product_type.product_picture_url
     *
     * @mbg.generated
     */
    public String getProductPictureUrl() {
        return productPictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_picture_url
     *
     * @param productPictureUrl the value for product_type.product_picture_url
     *
     * @mbg.generated
     */
    public void setProductPictureUrl(String productPictureUrl) {
        this.productPictureUrl = productPictureUrl == null ? null : productPictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_introduce
     *
     * @return the value of product_type.product_introduce
     *
     * @mbg.generated
     */
    public String getProductIntroduce() {
        return productIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_introduce
     *
     * @param productIntroduce the value for product_type.product_introduce
     *
     * @mbg.generated
     */
    public void setProductIntroduce(String productIntroduce) {
        this.productIntroduce = productIntroduce == null ? null : productIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.product_character
     *
     * @return the value of product_type.product_character
     *
     * @mbg.generated
     */
    public String getProductCharacter() {
        return productCharacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.product_character
     *
     * @param productCharacter the value for product_type.product_character
     *
     * @mbg.generated
     */
    public void setProductCharacter(String productCharacter) {
        this.productCharacter = productCharacter == null ? null : productCharacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.s_id
     *
     * @return the value of product_type.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.s_id
     *
     * @param sId the value for product_type.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.state
     *
     * @return the value of product_type.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.state
     *
     * @param state the value for product_type.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.create_date
     *
     * @return the value of product_type.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.create_date
     *
     * @param createDate the value for product_type.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_type.update_date
     *
     * @return the value of product_type.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_type.update_date
     *
     * @param updateDate the value for product_type.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}